### PR TITLE
[WIP] Mac builds

### PR DESCRIPTION
**Pull request by whophil**
## Description

Using PR for testing / visibility.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by whophil** [comment]
I am pausing my efforts on this, at least for a bit.

I can't correctly generate the bindings on Mac. The binding generation process needs to include `type_traits`, but even when I add the directory containing it to the includes, the binding process still fails with this type of error.

```
----------------------
DIAGNOSTIC INFORMATION
----------------------
---
SEVERITY: 4
LOCATION: <SourceLocation file '/Users/phil/anaconda3/envs/binder2/include/c++/v1/cstddef', line 44, column 15>
MESSAGE: 'stddef.h' file not found
---
Complete with 1 issues with lower than 4 severity not shown.
```

This doesn't cause the binding generation process to _fail_, it just results in incomplete bindings.

For my needs, I found that the [OCP](https://github.com/CadQuery/OCP) project already offers Win/Mac/Linux binaries, and for my project's needs it works the same.

**Comment by trelau** [comment]
Thanks for the contributions @whophil . There is also pythonocc https://github.com/tpaviot/pythonocc-core which may be of use to you. It uses SWIG whereas pyOCCT (and I believe OCP) uses pybind11, but they all effectively do the same thing.

**Comment by whophil** [comment]
I did make a little more progress on the mac bindings. As the latest build log shows, these are now failing on a `windows.h` include, which I assume means some files need to be added to Mac excludes. I think this is more in line with (or will eventually lead to)
issues discussed in #19 , but at least the CI is showing some relevant errors.

**Comment by trelau** [comment]
I cherry-picked some things from this PR and have been experimenting with this branch https://github.com/trelau/pyOCCT/tree/osx_support. It looks like there aren't anymore severe errors during the binding generation process, though not sure if everything if going to build and test successfully.

If you're working on osx locally, maybe you can try this branch?

**Pull request closed without merging**
