### PR TITLE
Update linux to 7.6.0

### PR DESCRIPTION
**Pull request by frmdstryr**
## Description

Update binder/config to use occt 7.6.0 on linux.

## Motivation and Context

For #94 , I don't have/use windows so someone else can fix that.

## How Has This Been Tested?
DeclaraCAD with py3.8.

## Screenshots (if appropriate):
occt-7 6 0

### CODE REVIEW

**Comment by trelau** [comment]
btw..i'm working on a new (rewritten) version of the python binder (i.e., pyOCCT_binder). it's running locally on OCCT 7.6.0 on windows. will share the repo in coming days

**Comment by frmdstryr** [comment]
Good to hear.. any chance it'll work with smesh too?

**Comment by trelau** [comment]
@frmdstryr yes, in theory. the main motivation for redoing pybinder was to make it more robust and modular so it can (in theory) be applied to SMESH (as part of pySMESH project). at one point i had SMESH packaged into pyOCCT but it seems like those deserve to be separate things (tho it adds complexity in the binding tool). i could be convinced either way if you have an opinion on the matter.

**Comment by frmdstryr** [comment]
I was playing around and got pySMESH 9.7 to compile with pyOCCT 7.6 ~~but it seems like SMESH can no longer import base classes from OCCT. It's just giving a "referenced unknown base type" at import time for anything that extends something from OCCT.  It's odd because I had it working with smesh 9.6... Idk if I messed something up or what changed. This wouldn't be a problem if it were all one library... but I still think they should be separate.~~ 

Edit: Nevermind, it works fine, I just missed a few types...

**Pull request closed without merging**
