### PR TITLE
Update binder to fix some missing enums

### PR DESCRIPTION
**Pull request by frmdstryr**
## Description

This updates the binder to the format in the pending PR and adds a test to check that the enum change works for one of the missing enums.

## Motivation and Context

In the current build some anonymous enums are missing, eg trying to import them fails and any functions that return them fail. I discovered this with `MeshVS_EntityOwner` but after adding a patch in the binder a grep shows these were missing:

```cpp
src/TDF.cxx-mod.attr("TDF_AttributeValidMsk") = py::cast(int(TDF_AttributeValidMsk));
src/TDF.cxx-mod.attr("TDF_LabelNodeImportMsk") = py::cast(int(TDF_LabelNodeImportMsk));
src/IVtk.cxx-py::enum_<IVtk_SelectionMode>(mod, "IVtk_SelectionMode", "Enumeration that describes all supported selection modes for 3D shapes. SM_None means that the shape should become non-selectable. SM_Shape makes the shape selectable as a whole. Other modes activate selection of sub-shapes of corresponding types.")
src/Graphic3d.cxx-mod.attr("Graphic3d_ZLayerId_UNKNOWN") = py::cast(int(Graphic3d_ZLayerId_UNKNOWN));
src/Graphic3d.cxx-mod.attr("Graphic3d_ArrayFlags_None") = py::cast(int(Graphic3d_ArrayFlags_None));
src/XCAFPrs.cxx-mod.attr("XCAFPrs_DocumentExplorerFlags_None") = py::cast(int(XCAFPrs_DocumentExplorerFlags_None));
src/Aspect.cxx-py::enum_<Aspect_PolygonOffsetMode>(mod, "Aspect_PolygonOffsetMode", "None")
src/Aspect.cxx-mod.attr("Aspect_VKeyFlags_NONE") = py::cast(int(Aspect_VKeyFlags_NONE));
src/MeshVS.cxx-mod.attr("MeshVS_BP_Mesh") = py::cast(int(MeshVS_BP_Mesh));
src/MeshVS.cxx-py::enum_<MeshVS_EntityType>(mod, "MeshVS_EntityType", "None")
src/MeshVS.cxx-mod.attr("MeshVS_DMF_WireFrame") = py::cast(int(MeshVS_DMF_WireFrame));
src/MeshVS.cxx-py::enum_<MeshVS_SelectionModeFlags>(mod, "MeshVS_SelectionModeFlags", "None")
src/BVH.cxx-mod.attr("BVH_Constants_MaxTreeDepth") = py::cast(int(BVH_Constants_MaxTreeDepth));
src/TObj.cxx-py::enum_<TObj_DeletingMode>(mod, "TObj_DeletingMode", "None")
```

## How Has This Been Tested?

Test added.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by trelau** [comment]
this is dependent on this PR, right? https://github.com/trelau/pyOCCT_binder/pull/21

**Comment by frmdstryr** [comment]
Only the enum change is needed. Could be cherry picked from https://github.com/trelau/pyOCCT_binder/pull/21/commits/23a0f9bda4b893035a5f9a3b513e05efc96646cd

**Comment by trelau** [comment]
in that case...should we make that it's own PR, get it merged in the binder, then can merge this? seems like it's a worthy PR by itself

**Comment by trelau** [comment]
Seams harmless, but for some reason all the windows builds failed with "compiler out of heap space" error. trying to re-run the jobs now since sometimes that error is not repeatable. a few ways to maybe address in the future (not sure if they are all feasible):
- Automatically split the larger files into separate ones to compile separately (e.g., Graphic3d)
- Increase machine specs used for github workflows (even possible?)
- Any compiler settings that could help?

This error is likely local due to machine specs on github, so not really a priority, but would be nice to get the workflows running reliably.

**Comment by frmdstryr** [comment]
Can you retrigger a build on the master branch and see if it's something github actions? It added two enums to the Graphic3d...

What about using clang instead of msvc for windows?

**Comment by trelau** [comment]
it doesn't look like i can retrigger main branch easily. will have to make some time to look at that. i've never used clang....maybe it's an option....i'm just a part-time hacker so it's not something i have any experience with yet 😄

**Comment by trelau** [comment]
@frmdstryr i updated my local project with this content and tested everything on windows https://github.com/trelau/pyOCCT/commit/383f2f2e924a2da86a6a5a75d0df76fbd592ea01

Let's close this PR

**Comment by frmdstryr** [comment]
Looks like its working :+1:

**Pull request closed without merging**
