### PR TITLE
Support for OCCT 7.5.0

### PR DESCRIPTION
**Pull request by trelau**
Support for OpenCASCADE 7.5.0. This also drops support for SMESH in this project and instead the Python bindings for SMESH will be developed and maintained in a separate project.

### CODE REVIEW

**Comment by frmdstryr** [comment]
Looks like the version also needs updated in `OCCT/__init__.py`

**Comment by trelau** [comment]
@frmdstryr good catch

**Comment by trelau** [comment]
@frmdstryr it looks like the compiler will sometimes run out of memory based on the random build failures? I don't think that is going to stop the PR, but know of any tricks to prevent that? The file could be broken into smaller files, but that would require work on the binder generator...

**Comment by frmdstryr** [comment]
Could add `j1` to ninja like the windows script.

**Pull request merged**
