### PR TITLE
Occt 750

### PR DESCRIPTION
**Pull request by frmdstryr**
Adds onto your WIP 7.5.0 branch.

## Description

1. Fixes a few import loops and changes due to deprecations
2. Some changes for linux (glew / X11) (wayland now seems to work)
3. Adds #73 

## Motivation and Context

Stay up with the latest and greatest.

## How Has This Been Tested?

Ran DeclaraCAD (on linux).

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by trelau** [comment]
Looks good. Thanks for the PR!

Are you making use of SMESH at all? I've been thinking about splitting pyOCCT into two projects: 1) pyOCCT (just OCCT bindings) and 2) pySMESH (SMESH bindings).

**Comment by trelau** [comment]
@frmdstryr nbd, but i noticed import guards were added but not any call guards. usually there are specific functions somewhere in the module that need the guarded module. I think they can be addressed one-by-one as needed, just a note for the future.

**Comment by frmdstryr** [comment]
Not using smesh, still need to learn that... But I like the idea of keeping them separate unless it's more of a hassle.

Oh yeah, I was just trying to get it going and didn't really understand how to use iguard and cguard until later... I'll see if I get some time to clean it up next week.

**Comment by trelau** [comment]
@frmdstryr just fyi i started working on this https://github.com/trelau/pySMESH

**Pull request merged**
